version: "3"

env:
  ENV: testing

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

vars:
  # --- Versioning ---
  # The Go import path for the package where version variables are defined
  PACKAGE_PATH: github.com/eng618/eng/cmd/version
  # Get the latest git tag, or commit hash if no tags
  VERSION:
    sh: git describe --tags --always --dirty --abbrev=0
  # Get the short commit hash
  COMMIT:
    sh: git rev-parse --short HEAD
  # Get the build date in ISO 8601 format
  DATE:
    sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
  # Construct the ldflags string
  LDFLAGS_STRING: '-X "{{.PACKAGE_PATH}}.Version={{.VERSION}}" -X "{{.PACKAGE_PATH}}.Commit={{.COMMIT}}" -X "{{.PACKAGE_PATH}}.Date={{.DATE}}"'
  # Add ldflags to Go build/install commands
  GO_BUILD_FLAGS: '-ldflags="{{.LDFLAGS_STRING}}"'
  # Output binary name
  BINARY_NAME: eng

tasks:
  # -----------------------------------------------------------------------------
  # Usage
  install:
    desc: Build the binary and install it to $GOPATH/bin
    cmds:
      - echo "Installing {{.PACKAGE_PATH}} version {{.VERSION}}..."
      # Use GO_BUILD_FLAGS for install
      - go install {{.GO_BUILD_FLAGS}} .
      - task: completion
    aliases:
      - "i"
    deps: # Ensure build runs first if needed, though go install builds anyway
      - build

  completion:
    desc: Generate Zsh completion script
    cmds:
      - echo "Generating Zsh completion..."
      # Run the locally built binary
      - ./{{.BINARY_NAME}} completion zsh > ~/.local/share/zsh-completions/_eng
    # Make sure build runs before completion generation
    deps:
      - build
    # Prevent re-running build if install already ran it
    # status:
    #   - test -f ./{{.BINARY_NAME}}

  # -----------------------------------------------------------------------------
  # Release helpers

  changelog:
    desc: "[DEPRECATED] Generate changelog and commit (Now automated by release-please)"
    cmds:
      - echo "Generating changelog..."
      - git-chglog -o CHANGELOG.md
      - git add --update
      - 'git commit -m "chore(CHANGELOG): update [skip-ci]"'
      - "echo Changelog updated and committed. Note: release-please now automates this on main."
    silent: true

  changelog-ci:
    desc: Generate changelog and commit (for CI)
    cmds:
      - task changelog

  changelog-hook:
    desc: Update changelog and amend current commit
    cmds:
      - echo "Updating changelog and amending commit..."
      - git-chglog -o CHANGELOG.md
      - git add CHANGELOG.md
      - git commit --amend --no-edit
      - echo "Changelog updated and commit amended."
    silent: true

  setup-hooks:
    desc: Set up git hooks for changelog automation
    cmds:
      - echo "Setting up pre-commit hook for changelog..."
      - mkdir -p .git/hooks
      - |
        cat > .git/hooks/pre-commit << 'EOF'
        #!/bin/sh
        # Auto-update changelog before commit
        if command -v git-chglog >/dev/null 2>&1; then
            echo "Updating changelog..."
            git-chglog -o CHANGELOG.md >/dev/null 2>&1
            git add CHANGELOG.md >/dev/null 2>&1
            echo "Changelog updated."
        else
            echo "Warning: git-chglog not found. Install with: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest"
        fi
        EOF
      - chmod +x .git/hooks/pre-commit
      - echo "Pre-commit hook installed. Changelog will be updated automatically before each commit."

  release-check:
    desc: Check goreleaser configuration
    cmds:
      - echo "Checking goreleaser configuration..."
      - goreleaser check

  release-clean:
    desc: Run goreleaser release with --clean
    cmds:
      - echo "Running goreleaser release..."
      # Goreleaser typically handles its own ldflags via .goreleaser.yaml
      # Ensure your .goreleaser.yaml is configured if you use goreleaser for releases
      - goreleaser release --clean

  release:
    desc: "[DEPRECATED] Perform a release (Now automated by release-please)"
    cmds:
      - echo "Manual release is deprecated. Releases are now automated via release-please on GitHub."
      - echo "To release, merge the 'release-please' PR on the main branch."
      - # task: release-clean
      - # task: changelog

  # -----------------------------------------------------------------------------
  # development

  build:
    desc: Build the binary locally
    cmds:
      - echo "Building {{.PACKAGE_PATH}} version {{.VERSION}}..."
      # Use GO_BUILD_FLAGS for build and specify output binary name
      - go build {{.GO_BUILD_FLAGS}} -v -o {{.BINARY_NAME}} .
    # Make output file available to other tasks
    generates:
      - ./{{.BINARY_NAME}}

  lint:
    desc: Run linter
    cmds:
      - echo "Running linter..."
      - golangci-lint run ./...

  lint-fix:
    desc: Run linter with auto-fix
    cmds:
      - echo "Running linter with auto-fix..."
      - golangci-lint run --fix

  test:
    desc: Run tests
    cmds:
      - echo "Running tests with coverage report..."
      - CGO_ENABLED=1 go test ./... -cover -race -coverprofile=coverage.out -covermode=atomic

  format:
    desc: Format Go code
    cmds:
      - gofmt -w .
      - golangci-lint fmt ./...

  format-check:
    desc: Check Go code formatting
    cmds:
      - |
        unformatted=$(gofmt -l .)
        if [ -n "$unformatted" ]; then
          echo "The following files are not formatted:"
          echo "$unformatted"
          echo "Run 'task format' to fix."
          exit 1
        else
          echo "All Go files are properly formatted."
        fi
    silent: true

  validate:
    desc: Run lint and tests
    cmds:
      - task: format
      - task: lint
      - task: test

  # -----------------------------------------------------------------------------
  # Module Support

  tidy:
    desc: Tidy go modules
    cmds:
      - echo "Tidying go modules..."
      - go mod tidy

  deps-reset:
    desc: Reset go.mod and tidy
    cmds:
      - echo "Resetting go.mod..."
      - git checkout -- go.mod
      - task: tidy

  deps-list:
    desc: List available module updates
    cmds:
      - echo "Listing module updates..."
      - go list -m -u -mod=readonly all

  deps-upgrade:
    desc: Upgrade dependencies and tidy
    cmds:
      - echo "Upgrading dependencies..."
      - go get -u -v ./...
      - task: tidy

  deps-cleancache:
    desc: Clean module cache
    cmds:
      - echo "Cleaning module cache..."
      - go clean -modcache

  list:
    desc: List all modules
    cmds:
      - echo "Listing all modules..."
      - go list -mod=mod all

  # -----------------------------------------------------------------------------
  # Tools (Maintenance & Automation)

  tools:test:
    desc: Run tests for maintenance tools
    dir: tools
    cmds:
      - echo "Testing maintenance tools..."
      - go test -v ./...

  tools:lint:
    desc: Lint maintenance tools
    dir: tools
    cmds:
      - echo "Linting maintenance tools..."
      - golangci-lint run ./...
